### ISSUE TITLE
Doesn't seem to work on custom entities.

### ISSUE THREAD

**Issue by WiktorProj** [VikkiVuk/Pehkui-for-MCreator#2]
The scaling doesn't seem to work on custom entities

**Comment by krissedout** [comment]
Could you please provide me with more details? I will need your mcreator version, generator type, procedure (in a screenshot), and, if possible, your codebase repo.

**Comment by WiktorProj** [comment]
Nevermind, I was just using the wrong entity block ¯\_(ツ)_/¯
