### ISSUE TITLE
Why is there no base?

### ISSUE THREAD

**Issue by WiktorProj** [VikkiVuk/Pehkui-for-MCreator#3]
Why is there no base?
There is a command dedicated to that.

**Comment by krissedout** [comment]
Hi, I didn't notice you also opened an issue. I responded to you on the plugin page regarding this, i will here too. This plugin doesn't call pehkui commands. Instead, it uses the actual API. I didn't think it was necessary to add the BASE option as I didn't find a use case for it. However, I will add it in the next update, which will be coming next week, most likely as i am currently on break.
